<div class="container marketing nlInfo">
   <h2>National Legal Center-Privacy Policy</h2>
     <h2>Privacy Policy & Terms of Use</h2>
     <p>As professionals engaged in the provision of legal services to clients nationwide, National Legal Center is committed to protecting the privacy of confidential and personal information, including personal data relating to individuals who may be clients, staff, agents, lawyers, law students, job applicants or others inside or outside the Firm. It has always been and remains the policy of the Firm to comply with the rules of professional conduct which impose a duty to preserve and protect confidential client information upon lawyers and their associated personnel.</p>
     <p>This notice applies to National Legal Center and DBA's and AKAs within the National Family of companies, such as National Legal Law Offices, National Legal Systems, and covers affiliates and other entities and/or names we do business as or with, that provide administrative services to clients such as Client Support    Services and National Legal Support System. (Collectively, the Firm or National Legal) For more information about our family of companies you may contact us    at the email or mailing address just above.</p>
     <p>This Privacy Statement is based on the privacy and data protection principles common to the states in which we service. We apply it in light of our over-   arching obligations to comply with law, to preserve client confidentiality and to represent our clients as effectively as possible within the bounds of the law.    This Statement is intended to summarize the Firm's data protection practices generally, and to advise our clients, interested law students, job applicants,    website visitors, and other third parties about the Firm's privacy policies that may be applicable to them.   This Privacy Statement is specifically addressed to parties outside the Firm who provide personal information to the Firm or who visit or use the Firm's websites.</p>
     <h2>No Legal Services or Attorney-Client Relationship</h2>
     <p>Although National Legal Center may provide information concerning potential legal issues, it is not a substitute for legal advice from qualified counsel. You should not and are not authorized to rely on our websites as a source of legal advice. You may also not rely on any discussions you have with non-attorneys, representatives or affiliates as legal advice. Discussing your case with a representative or attorney does not create any attorney-client relationship between you and National Legal unless agreed to in writing.</p>
     <p>Please be further advised that making an inquiry through one of our websites or contacting us by email or phone, registering for a seminar, requesting email alerts or sending email or other correspondence to National Legal Center or any of its attorneys does not and will not create an attorney-client relationship.</p>
     <p>If you are not currently a client of National Legal Center, your email or other correspondence will not be privileged and may be disclosed to other persons.    Unless and until National Legal Center and/or an attorney has formally established an attorney-client relationship, as evidenced by a signed engagement agreement, please do not send any confidential information or any information that you would expect to be maintained in confidence.</p>
     <p>If you communicate with us by email in connection with a matter for which we already represent you, you should note that the security of Internet email is    uncertain. By sending sensitive or confidential email messages that are not encrypted, you accept the risks of such uncertainty and possible lack of confidentiality.</p>
     <h2>Terms of Use and Privacy Policy</h2>
     <p>Your use of any National Legal website, its facilities or use of our service constitutes your agreement to the terms of these Legal Notices and Terms of Use set forth in this notice.  The terms of Legal Notices and Terms of Use, is subject to change at any time and for any reason without notice. National Legal will make such changes by posting them at our website. We encourage you to check our websites periodically for any changes.</p>
     <p>Your use of our websites or contacting our following the posting of changes to these terms will mean you accept those changes.</p>
     <h2>Proprietary Rights</h2>
     <p>We understand the importance of privacy to visitors, people making inquiries of service and clients, so we have established this Privacy Policy to let you know what information we may collect from you and how we may use and share that information. Please take a moment to review the terms of our Privacy Policy. By using one of our websites, making an inquiry to us by phone or email you agree to and accept the terms of our Privacy Policy. If you do not agree to the terms of this Privacy Policy, please do not use our websites or contact us for information or questions.</p>
     <h2>Disclaimer</h2>
     <p>Materials at our websites are for informational purposes only and do not constitute advertising, a solicitation or legal advice. Written or verbal Information we provide to you when making an inquiry does not constitute advertising, a solicitation or legal advice. The information is provided only as general information that may or may not reflect the most current legal developments; accordingly, information is not promised or guaranteed to be correct or complete. Further, prior results do not guarantee a similar outcome. National Legal Center expressly disclaims all liability in respect to actions taken or not taken based on any provided to you and all contents of our websites.</p>
     <p>National Legal does not wish to represent anyone desiring representation based upon viewing one of our websites in a state or other jurisdiction where we do not provide service or comply with all laws and ethical rules of that state or jurisdiction.</p>
     <p>National Legal Center (National Legal) believes you have a right to the expectation of privacy and security. Our Privacy Policy describes how information is gathered, how the information is used that we collect and the steps we take to safeguard your privacy and protect your personal information.</p>
     <p>In our effort to ensure that our Privacy Policy are current and that we are responsive to changes in relevant laws and regulations, developments in technology, our business plan and activities, as well as our websites and business activities, we reserve the right to change and/or amend our Privacy Policy from time to time. Use of our website(s) constitutes your consent to the current version of our Privacy Policy.</p>
     <p>Our Privacy Policy may be modified, updated, and changed at any time and we will inform you of such pursuant to relevant laws and regulations.  To review the most recent copy of our Privacy Policy, please visit www.nationallegal.com.</p>
     <p>Questions regarding our Privacy Policy and our position, as well as your rights under our Privacy Policy, please contact support@nationallegal.com.</p>
     <p>Please use of the following means to contact us should you have any questions or concerns about our Privacy Policy.</p>
     <p>Email:    support@nationallegal.com</p>
     <p>US Mail:  National Legal Center, PO Box 835, Candia, NH, 03034</p>

     <h2>What Does This Privacy Policy Cover?</h2>
     <p>National Legal owns, leases, supervises and operates several websites, as well as a number of websites and/or domains that point to one or another of our websites.</p>
     <p>From time to time, we may add additional websites and/or domains to our portfolio. Whether or not any particular site is specifically identified in this Privacy Policy, this Privacy Policy applies to any website owned, leased, supervised and/or operated by National Legal Center. This notice also applies to all companies within the National Legal family of companies. This Privacy Policy covers affiliates, and other entities and/or names we do business as, National Legal Center, National Legal Law Offices, National Legal Systems, as well other companies that provide administrative services to our clients such as Client Support Services, National Legal Support Systems, For more information about our family of companies you may contact us at the email or mailing address just above.</p>
     <p>This Privacy Policy covers what we do with any personal information you may submit or authorize us to obtain, as well as any other information that we may gather when you access any of our websites. This Privacy Policy also covers any of your personal and other information that any of our business partners may share with us.</p>
     <p>Our policies and procedures apply only to websites owned, leased, controlled and and/or operated by us and those identified in this Privacy Policy. It does not include websites maintained by other companies or to any website to which we may link or to unrelated businesses with which we may share information.</p>
     <h2>What is "Personal Information"?</h2>
     <p>Personal information is any information that you provide to us or authorize us to obtain that identifies you, personally, or that can be logically associated with you. Examples of personal information would be your name, your address, your e-mail address and your Social Security Number. Demographic information such as gender, age, zip code, etc., is generally not considered personal information.</p>
   <h2>Why Do You Need To Collect My Personal Information?</h2>
     <p>We collect and use personal information to provide a response to your inquiries about services we offer as well as those of our business partners. In order to provide service to you, we must collect personal and confidential information. We also collect personal and other information to make you aware of products and services that are likely to be of interest to you.</p>
     <h2>What Personal and Other Information Do You Collect and/or Maintain?</h2>
     <p>We collect and maintain the information you provide to us and/or one of affiliates and referral sources on applications or forms. Examples of information are: your income, accounts, name, address, telephone number and, in some cases, your Social Security number.</p>
     <p>Depending upon the product or service you request, you may also be asked to provide additional information, such as the amount of your current unsecured debt and the identity of your creditors, information about your mortgage and other financial and personal information.</p>
     <p>Information we receive about your transactions with us, our affiliates or others, such as your account balance, payment history and credit card usage.  Information we receive from a third party, such as a credit bureau, about your credit history or employment status. Information, such as your e-mail address, that you provide to us when you register to receive communications from us or when you communicate with us through our customer service facility, or otherwise correspond with us.</p>
     <p>We also collect other information which may be defined as any information that is not directly associated with you. Examples of this information are: your zip code, State and City, Line of work etc. We may also receive information about you from other on-line or off-line sources. For example, if you provide us with personal information along with an appropriate authorization we may request and obtain a credit report and credit score.</p>
     <p>In addition, when you provide contact details for transaction requests such as scheduling an appointment or requesting status updates, we will need to access your confidential information in order to provide a status of your account.</p>
     <p>From time to time, we may use the contact information to keep you updated about future offers or promotions unless you opt-out online or otherwise notify us.  We may also use the information we collect about you in order to, but not limited to:</p>
     <ul>
    <li>Learn more about your interest in the products or services we offer</li>
    <li>Enroll customers who desire other services we offer</li>
    <li>Open customer files and establish their accounts</li>
    <li>Provide customer service</li>
    <li>Negotiate resolutions of our customers' debts
     (According to the terms and conditions of their written agreements)</li>
    <li>Learn how to improve our products or services</li>
    <li>Provide opportunities for our affiliates and other companies to inform you about the products or services they offer that may interest you</li>
    <li>Share aggregated statistical data with our business partners or for public relations</li>
</ul>
     <h2>How Do You Use The Personal and Other Information You Collect?</h2>
     <p>To keep you informed about services you may be interest in, we use information you supply to us, or information that you authorize us to obtain for a number of purposes. Examples of this are responding to your inquiries and in order to service your account.</p>
     <p>We may also use your personal and other information to enhance your experience on our website(s) by displaying content based on your preferences and/or to send information to you about additional products or services in which you may be interested. We may "depersonalize" your personal information to enable us to use that information, aggregated with the information of others, for research, analysis and modeling purposes.</p>
     <p>Occasionally, receive medical or health information from a customer if a customer lists a medical debt with us. We do not share medical or health information, including information received from third parties, among our companies, except to maintain accounts, process transactions or service customer requests to the extent permitted by law.</p>
     <h2>Aggregate Information</h2>
     <p>From time to time, we may collect general, non-personal, statistical information about the use of the Site, such as how many visitors visit a specific page on the Site, how long they stay on that page and which hyperlinks, if any, they "click" on. We collect this information through the use of "cookies" and other tracking technologies, which are discussed in greater detail below. We collect this information in order to determine which areas of the Site are most popular and to enhance the Site for visitors. We may group this information into aggregate visitor data in order to describe the use of the Site to our existing or potential business partners or other third parties, or in response to a government request. We may also group preferences information that we collect from visitors into aggregate data for the same purposes. However, please be assured that this aggregate data will in no way personally identify you or any other visitors to the Site.</p>
     <h2>With Whom Do You Share My Information?</h2>
     <p>If you submit a request for a product or service, we will share the personal and other information you supply with those product and service providers that    have agreed to participate in our network. Generally, these product and service providers are prohibited from using the information we provide to them for any other purpose, including using your information for other, unrelated marketing purposes.</p>
     <p>By submitting your request you are consenting to being contacted by us or by one of our affiliates through any means, based on the information you provide to    us. You inquiry to us waives any rights you may have if you have opted into the National Do Not Call List administered by the Federal Trade Commission, as well as any state Do Not Call List or the Do Not Call List of any specific institution.  If, after being contacted by us and you do not wish to be contacted again, you must make a specific request to the person contacting you. If, after being contacted an affiliate or service provider, and no longer wish to be contacted by that person again, you must make a specific request to the product or service provider, not to National Legal Center.</p>
     <p>As permitted by law, we may also share your personal and other information with a third party that provides a service or supplies a specific functionality to us, such as a call center operator, attorney, or bank. These service providers will be provided only with the information necessary for them to perform their functions and are not allowed to share any of the provided information with others for any purpose whatsoever.</p>
     <p>Additionally, we may share your personal and other information within our affiliate companies for a number of purposes, for example, to process your requests and to keep you informed of services that may be of interest to you. Any person with whom we share your personal information is also required to comply with federal and state privacy regulations and will have its own privacy policies that should be made available to you at the time you are first contacted.</p>
     <h2>Are There Any Other Circumstances Where You Disclose My Information?</h2>
     <p>We may be required to share your information with law enforcement or government agencies in response to subpoenas, court orders or other forms of legal process. We may elect to share information when, in our reasonable judgment, such sharing is necessary or appropriate for the investigation or prevention of illegal activities, including actual or suspected fraud, real or potential threats to the physical safety of any person or otherwise as required by law.</p>
     <p>In addition, if we are merged with, or acquired by, another company the successor company will have access to all of the information collected and maintained by us. In such a circumstance, the successor company would continue to be bound by the terms and conditions of this Privacy Policy.</p>
     <h2>How Do You Collect Information Online?</h2>
     <p>We collect certain types of non-personal information and technical data from each visitor to our website(s). For example, when you click on a banner advertisement or text link that is associated with one of our websites, the banner or text placement, along with the time of your visit, your Internet Protocol address and other path-related information, is sent to us. Similarly, the page requests you make when you visit our website(s) are stored and used by us. We use this information, none of which is or can be personally associated with you, for statistical and analytic purposes, to help us understand which page views are most appealing to our customers and to help us improve the likelihood that we will be able to offer you only products or services in which you have a genuine interest.</p>
     <h2>What Are Cookies?</h2>
     <p>"Cookies" are small files that are placed automatically on your computer system when you visit a website. Cookies enable a website to recognize you as a return visitor and, by keeping track of your website activity, help us identify which pages to serve to you while reducing the time it takes for those pages to load. Cookies enable us to personalize and enrich your experience and are not tied in any way to your personal information.</p>
     <p>If you do not wish to accept cookies or if you wish to remove cookies that remain in your browser following the close of your browser session, you may adjust the settings on your web browser to prevent cookies from being placed on your hard drive. Please review your web browser "Help" file to learn the proper way to modify your cookie settings.</p>
     <h2>Do You Use Any Other Advertising Technology?</h2>
     <p>We may use third party advertising technology to serve ads on our website(s) and on the websites where we advertise. Generally, advertisements are served by ad networks, such as DoubleClick, that are independent of us. Third party servers may employ cookies or action tags to measure advertising effectiveness, target advertising to individuals and for other purposes.</p>
     <h2>What Are Web Beacons?</h2>
     <p>"Web beacons" are, like cookies, small files that enable an ad server to recognize a visitor's cookie when the visitor returns to a particular site. Web beacons may also be used in e-mail advertising to help track which e-mail messages have been opened. Web beacons are used to track the movement of visitors to our sites and, like cookies, are not tied to any personal information.</p>
     <h2>How Do You Safeguard The Information You Collect?</h2>
     <p>The security of your personal information is a very high priority for us and we take a number of steps to safeguard it. Some of the measures we take are:</p>
     <ul>
     <li>Limiting access to personal information to those employees who are critical to the delivery of products and services to you.</li>
     <li>Implementing appropriate physical, electronic and procedural safeguards to guard against unauthorized access or use.</li>
     <li>Requiring appropriate consents and protections from our business partners before we share any personally identifiable information.</li>
  </ul>
     <p>National Legal and its affiliates use commercially reasonable physical and technical security measures to protect all personal information in our possession. Sensitive information such as Social Security numbers are encrypted using secure sockets layer encryption from the time of your submission and while it is stored by us. We cannot, however, guarantee or warrant the absolute security of any system or that any information we hold will not be accessed, disclosed, altered or destroyed.</p>
     <h2>How Long Do You Retain My Personal Information?</h2>
     <p>We normally retain your personal information for a reasonable time after our customer relationship with you ends, and in any event, generally not less than one (1) year from the date we first collect it. For legal reasons, we may sometimes be required to retain personal information for a longer period. Under certain circumstances, Federal and/or state law may require us to retain your personal information for different periods of time.</p>
     <p>We may disclose personal information about former customers to affiliated and other persons in the same way and of the same types as we disclose for customers.</p>
     <p>Non-personal information may be retained indefinitely.</p>
     <h2>Can I Correct or Remove My Personal Information?</h2>
     <p>If you believe there are factual errors in any of the information you have submitted to us, please contact us and advise us of the error. To protect your privacy and security we may require that you verify your identity before we make any requested changes to personal information.</p>
     <h2>What Choices Do I Have?</h2>
     <p>You can always elect not to provide personal information to us, although if you do not complete and submit the information we ask for we may not be able to provide you with the most complete responses or you may not be able to access all the available features.</p>
     <h2>Choices You May Make for Your Privacy</h2>
     <p>You may choose to limit the way we share information about you. You may also choose to limit the solicitations we send you. These choices are referred to as "opt-outs."</p>
    <h2> I. Sharing of Information Outside of the National Legal Family of Companies</h2>
     <p>If you do not want us to disclose nonpublic personal information about you outside the National Legal family of companies, you may choose to opt out of those disclosures. In other words, you may tell us not to share this information and we will not, except in those cases where we may be required or permitted by law.</p>
     <p>For example, required disclosures may be made to law enforcement and regulators, while permitted disclosures may be made to vendors assisting us in opening, maintaining or servicing your account. (CA and VT Residents: To the extent state law applies, we will not disclose information about you outside the Freedom Financial family of companies, except as required or permitted by law.)</p>
<h2>II. Use and Sharing of Information among Companies in the National Legal Family</h2>
    <h2> Affiliate Sharing: </h2>
     <p>We may share your credit information within the National Legal family of companies. Credit information includes financial information you may share with us or credit history that we may obtain from credit bureaus. If you do not want us to share your credit information with other companies in the National Legal family, you may choose to opt out. (VT Residents: To the extent state law applies, we will not disclose credit information about you within the National Legal family of companies except as required or permitted by law.) If you opt out, we will not share your credit information with other companies in the National Legal family.</p>
       <h2> Affiliate Marketing: </h2>
        <p>Companies in the National Legal family may market their products and services to you based on information received from other companies in the National Legal family. This may include any information collected about you including your income, your account history, and your credit score. If you would like to limit the offers you may receive based on this shared information, you may choose to opt out. If you opt out, we will not market products or services to you based on information received from other companies in the National Legal family, except as expressly permitted by law. This limitation will not apply in certain circumstances, such as if you ask to receive information from a National Legal company.</p>
       <h2> III. How to Opt-Out</h2>
        <p>Your opt-out choices will continue to apply until you tell us to change them, except with respect to limits on solicitations which we will honor for the time periods required by law. If you have previously opted out based on a Freedom Financial notice and would like to keep the same preferences you do not need to opt out again.</p>
        <h2>Joint/Multiple Accounts:</h2>
        <p>Your opt-out choices will apply to all of your consumer accounts within the Freedom Financial family of companies, including joint accounts. For a joint account, an opt-out choice made by one joint account holder will only apply to that account holder.</p>
       <h2> Applicants:</h2>
        <p>Unless otherwise notified, applicants who do not become our customers may not make certain privacy elections.</p>
        <p>To exercise one or more of your opt-out choices described:</p>
        <p>Call us toll free: 1-800-728-5285</p>
        <p>To opt out of e-mail solicitations email support@nationallegal.com</p>
        <p>If you wish to stop receiving e-mails from us or from a third party e-mail service, we recommend you follow the opt-out instructions included in the e-mail.</p>
        <p>NV Residents: Pursuant to state law, if you would like more information about telemarketing solicitations please contact us at 1-800-728-5285 or write to us at: National Legal Center; PO Box 835; Candia, NH, 03034<p>
        <p>You may also visit our Web site at www.nationallegal.com. If you would like more information about Nevada's law regarding corporate do-not-call registries, please contact the Bureau of Consumer Protection, Office of the Nevada Attorney General at 555 E. Washington Street, Suite 3900, Las Vegas, Nevada 89101. Telephone Number: 1-702-486-3132. E-mail: BCPINFO@ag.state.nv.us</p>
       <h2>Do You Use My Personal Information to Contact Me Without Permission?</h2>
        <p>This Privacy Policy constitutes National Legal Do Not Call Policy under the Telephone Consumer Protection Act for all consumers and is pursuant to state law. When you talk with us by telephone your conversation may be monitored or recorded by us. We may maintain an internal Do Not Call preference list or utilize the services of third parties to maintain the list.</p>
        <p>Do Not Call requests will be honored within 30 days and will be effective for at least five years from the date of the request. No telemarketing calls will be made to residential or cellular phone numbers that appear on the Do Not Call list.</p>
        <p>National Legal has a strict "anti-spam" policy for itself and its business partners and vendors. You will not receive National Legal emails unless you submit on email address to us or register on one of our websites to receive communications, such as our newsletter.</p>
        <p>You may tell us not to solicit you at your postal mailing address, telephone number or e-mail address. If you elect not to receive marketing offers by postal mail, telephone and/or e-mail, please note that we may continue to contact you as necessary to service your account and for other no marketing purposes. We may also continue to provide marketing information in your regular account mailings and statements, including online and electronic communications.<p>
        <p>To receive our newsletter via e-mail you must sign up on one of our websites. If you decide at a later time that you no longer wish to receive our newsletter, you may unsubscribe using the "unsubscribe" link on each newsletter that you receive. If you have any problems unsubscribing, please contact us immediately at support@naionallegal.com</p>
        <h2>Social Security Numbers</h2>
        <p>Often we do not collect your Social Security number but if we do, our Privacy Policy (1) protects the confidentiality of Social Security numbers, (2) prohibits unlawful disclosure of Social Security numbers, and (3) limits access to Social Security numbers.</p>
        <h2>Testimonials</h2>
        <p>If you submit a testimonial to us, we may your use testimonial as we deem fit. We will generally redact your last name and other personal information it given to us in your testimonial. We may post a photo of you if you provide us one or we may use a fictitious stock photo.</p>
        <p>Please be aware that any personally identifiable information you submit as a testimonial to be posted can be read, collected, or used by the general public, and could be used to send you unsolicited messages. We are not responsible for the personally identifiable information you choose to include in any testimonial you choose to submit. If at any time you decide to remove your testimonial, please contact us via e-mail or postal mail.</p>
        <h2>A Special Note about Children's Privacy</h2>
        <p>We do not knowingly collect, use or share personal information about visitors under 18 years of age. If you are under 18 years of age, you can use the products and/or services offered on our website(s) only in conjunction with your parents or guardians. Special Notification for California Residents California residents who provide us with their personal information may request certain information regarding disclosures made to third parties for direct marketing purposes, including the names and address of those to whom such disclosures have been made. Such requests must be submitted to us at the following mailing address: California Privacy Request, National Legal Center, PO Box 835, Candia, NH, 03034. This request may be made no more than once per calendar year</p>

  </div>
